### ISSUE TITLE
logd大部分都是error

### ISSUE THREAD

**Issue by ysicing** [shenshouer/shadowsocks#8]
最近日志基本都是error
"error getting request 202.113.135.*:2919 133.130.100.*:* addr type 6 not supported"

**Comment by shenshouer** [comment]
这个应该不影响代理的访问

**Comment by ysicing** [comment]
最近不知道咋回事，感觉很不稳定似得

**Comment by andy-zhangtao** [comment]
出现这个问题有两种可能性：
1. 端口，密码不匹配，导致解密失败。 type N N取的是解密后的数据头字节，用来判断走IPV4还是IPV6或者balabala..
2. client 和 server ota不匹配。 server 不支持OTA，client启用了OTA。 或者server强制OTA，client没有启用。 都会导致解密失败。

**Comment by ysicing** [comment]
可能是第二种，`ota=false connOta=false`

**Comment by andy-zhangtao** [comment]
我发现还有第三种可能，是网络丢包率太高，导致数据包不完整造成解密失败。
如果使用过程中，同一个客户端偶尔出现一些这样的Error，那么应该就是这种情况。

**Comment by ysicing** [comment]
Get
<del>最近日本机房很不稳定╮(╯▽╰)╭
